"""initial db

Revision ID: ad78d893112f
Revises:
Create Date: 2026-01-08 09:49:40.507024+00:00

"""

# revision identifiers, used by Alembic.
revision = "ad78d893112f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
